
export const MEMBRE_FIELDS = [
  {
    label: "Pseudo",
    type: "text",
    name: "pseudo",
    id: "Pseudo",
    placeholder: "Pseudo",
  },
  {
    label: "Email",
    type: "text",
    name: "email",
    id: "email",
    placeholder: "votre email",
  },
  {
    label: "Password",
    type: "password",
    name: "password",
    id: "password",
    placeholder: "mot de passe",
  },
  {
    label: "Nom",
    type: "text",
    name: "nom",
    id: "nom",
    placeholder: "votre nom",
  },
  {
    label: "Prenom",
    type: "text",
    name: "prenom",
    id: "prenom",
    placeholder: "votre prénom",
  },
  {
    label: "Civilite",
    name: "civilite",
    id: "civilite",
    placeholder: "Selectionner votre civilité",
    opt1: "homme",
    opt2: "femme",
    opt3: "x",
  },
  {
    label: "Role",
    name: "role",
    id: "role",
    placeholder: "Selectionner un role",
    opt1: "admin",
    opt2: "superAdmin",
    opt3: "user",
  },
];
export const SIGN_FIELDS = [
  {
    label: "Email",
    type: "text",
    name: "email",
    id: "email",
    placeholder: "votre email",
    icon: "bi bi-envelope-at-fill",
  },
  {
    label: "Password",
    type: "password",
    name: "password",
    id: "password",
    placeholder: "mot de passe",
    icon: "bi bi-shield-lock-fill",
  },
];

export const REGISTER_FIELDS = [
  {
    label: "Nom",
    type: "text",
    name: "nom",
    id: "nom",
    icon: "bi bi-person-fill",
    placeholder: "Votre nom",
  },
  {
    label: "Prenom",
    type: "text",
    name: "prenom",
    id: "prenom",
    icon: "bi bi-person-fill",
    placeholder: "Votre prénom",
  },
  {
    label: "Pseudo",
    type: "text",
    name: "pseudo",
    id: "Pseudo",
    icon: "bi bi-person-fill",
    placeholder: "Pseudo",
  },
  {
    label: "Email",
    type: "text",
    name: "email",
    id: "email",
    icon: "bi bi-envelope-at-fill",
    placeholder: "Votre email",
  },
  {
    label: "Password",
    type: "password",
    name: "password",
    id: "password",
    icon: "bi bi-shield-lock-fill",
    placeholder: "Mot de passe",
  },
  {
    label: "Civilite",
    name: "civilite",
    id: "civilite",
    icon: "bi bi-gender-trans",
    placeholder: "Selectionner votre civilité",
    opt1: "homme",
    opt2: "femme",
    opt3: "x",
  },
];
